; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-core2]
platform = espressif32@6.1.0
board = m5stack-core2
framework = arduino

; Enable WiFi and HTTPClient for R2 upload
build_flags =
	-DBOARD_HAS_PSRAM

; Monitor settings
monitor_filters = esp32_exception_decoder
monitor_speed = 115200

lib_deps =
	m5stack/M5Core2@^0.1.9
	sparkfun/SparkFun u-blox GNSS Arduino Library@^2.2.27
	bblanchon/ArduinoJson@^6.21.0

; Test configuration
[env:native]
platform = native
debug_test = no
test_framework = unity
build_flags =
    -DTESTING
    -DENV_NATIVE
    -Itest/native/mocks
    -Iinclude
    -Isrc
lib_deps =
    mbedtls
build_src_filter =
    +<*> -<.git/>
    +<r2.cpp>

[env:test_esp32]
extends = env:m5stack-core2
debug_test = no
test_framework = unity
build_type = test
build_flags =
    ${env:m5stack-core2.build_flags}
    -DTESTING